#!/bin/bash
#BSUB -J PD_scRNAseq_rmarkdown	    # Name of job
#BSUB -P acc_ad-omics		    # Project to charge time
#BSUB -q premium		    # Target queue for job execution
#BSUB -n 12			    # Number of cores required
#BSUB -R span[hosts=1] 		    # All cores from N nodes
#BSUB -R rusage[mem=4000]	    # Memory per core
#BSUB -W 2:00			    # Time requested
#BSUB -m manda			    # Minerva partition requested
#BSUB -oo /dev/PD_scRNAseq.out      # Log file for standard output (overwrite)
#BSUB -eo /dev/null 		    # log file for standard error (overwrite)
#BSUB -L /bin/bash	 	    # Script shell language (/bin/tcsh, /bin/ksh etc.)
    
module load R pandoc
Rscript seurat_params.R 'protein_coding' F 0.6