#!/bin/bash
#BSUB -J PD_scRNAseq_res1.0_nCores4_mem15000    # Name of job
#BSUB -P acc_ad-omics		    # Project to charge time
#BSUB -q premium		    # Target queue for job execution
#BSUB -n 2		    	    # Number of cores required
#BSUB -R span[hosts=1]		    # Number of cores per host 
#BSUB -R rusage[mem=30000]	    # Memory per core
#BSUB -W 2:00			    # Time requested 
#BSUB -oo /dev/PD_scRNAseq.out      # Log file for standard output (overwrite)
#BSUB -eo /dev/PD_scRNAseq.error.out	    # log file for standard error (overwrite)
#BSUB -L /bin/bash	 	    # Script shell language (/bin/tcsh, /bin/ksh etc.)
    
module load R pandoc/1.19.2.1
Rscript seurat_params.R 'protein_coding' F .2 2 30